Kar/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^songs/', include('songs.urls', namespace="songs")),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.karaoke_welcome, name='welcome'),
]

project/karaoke/karaoke/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url(r'^$', views.home, name='home'),
]

project/karaoke/songs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'performer/(?P<pk>\d+)/$', views.performer_detail, name='performer'),
    url(r'song/(?P<pk>\d+)/$', views.song_detail, name='detail'),
    url(r'', views.song_list, name='list'),
]

songs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'performer/(?P<pk>\d+)/$', views.performer_detail, name='performer'),
    url(r'song/(?P<pk>\d+)/$', views.song_detail, name='detail'),
    url(r'', views.song_list, name='list'),
]

project/karaoke/songs/models.py
from django.db import models

# Write your models here

songs/models.py
from django.db import models


# Write your models here
class Performer(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Song(models.Model):
    # created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    length = models.IntegerField()
    performer = models.ForeignKey(Performer)

    class Meta:
        ordering = ['title',]

    def __str__(self):
        return self.title + ' by ' + self.artist

Kar/views.py
from django.shortcuts import render, render_to_response


def karaoke_welcome(request):
    return render(request, 'home.html')

project/karaoke/karaoke/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

project/karaoke/songs/views.py
from django.shortcuts import render

songs/views.py
from django.shortcuts import render, get_object_or_404

from .models import Performer, Song

def song_list(request):
    songs = Song.objects.all()
    return render(request, 'songs/song_list.html', {'songs': songs})


def song_detail(request, pk):
    song = get_object_or_404(Song, pk=pk)
    return render(request, 'songs/song_detail.html', {'song': song})


def performer_detail(request, pk):
    performer = get_object_or_404(Performer, pk=pk)
    return render(request, 'songs/performer_detail.html', {'performer': performer})

project/karaoke/songs/templates/songs/performer_detail.html
{% extends 'base.html' %}

{% block title %}{{ performer }}{% endblock %}

{% block content %}
<h2>{{ performer }}</h2>
{% endblock %}

project/karaoke/songs/templates/songs/song_detail.html
{% extends 'base.html' %}

{% block title %}{{ song.title }}{% endblock %}

{% block content %}
<h2>{{ song.title }}</h2>

<p>By {{ song.artist }}</p>
<p>Sung by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></p>
{% endblock %}

project/karaoke/songs/templates/songs/song_list.html
{% extends 'base.html' %}

{% block title %}Upcoming Songs{% endblock %}

{% block content %}
<h2>Upcoming Songs</h2>

<ul>
    {% for song in songs %}
    <li><a href="{% url 'songs:detail' pk=song.pk %}">{{ song }}</a> performed by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

project/karaoke/templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %} - Django Karaoke</title>
    </head>
    <body>
        <h1>Django Karaoke!</h1>
        <p><a href="{% url 'songs:list' %}">Upcoming Songs</a></p>
        
        {% block content %}{% endblock %}
    </body>
</html>

project/karaoke/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

songs/templates/songs/performer_detail.html
{% extends 'base.html' %}

{% block title %}{{ performer }}{% endblock %}

{% block content %}
<h2>{{ performer }}</h2>
    Upcoming songs:
    <ol>
        {% for song in performer.song_set.all %}
            <li>{{ song.title }} by {{ song.artist }} </li>
        {% endfor %}

    </ol>
{% endblock %}

songs/templates/songs/song_detail.html
{% extends 'base.html' %}

{% block title %}{{ song.title }}{% endblock %}

{% block content %}
<h2>{{ song.title }}</h2>

<p>By {{ song.artist }}</p>
<p>Sung by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></p>
{% endblock %}

songs/templates/songs/song_list.html
{% extends 'base.html' %}

{% block title %}Upcoming Songs{% endblock %}

{% block content %}
<h2>Upcoming Songs</h2>

<ul>
    {% for song in songs %}
    <li><a href="{% url 'songs:detail' pk=song.pk %}">{{ song }}</a> performed by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %} - Django Karaoke</title>
    </head>
    <body>
        <h1>Django Karaoke!</h1>
        <p><a href="{% url 'songs:list' %}">Upcoming Songs</a></p>
        
        {% block content %}{% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}